steps:
  #build server
  - name: gcr.io/cloud-builders/docker
    id: "signout-backend"
    args:
      [
        "build",
        "-f",
        "Dockerfile",
        "-t",
        "$_IMAGE_NAME",
        ".",
      ]
  #run docker-compose
  - name: 'docker/compose:1.28.2'
    args: 
      [
        '-f',
        'docker-compose.yml',
        'up', 
        '-d'
      ]
    id: 'tests:docker-compose'
    waitFor: ['signout-backend']
  #run integration tests
  - name: gcr.io/cloud-builders/docker
    id: 'tests:integration'
    entrypoint: 'bash'
    waitFor: ['tests:docker-compose']
    args: ['./scripts/run-integration-tests.sh']
  #run e2e tests
  - name: gcr.io/cloud-builders/docker
    id: 'tests:e2e'
    entrypoint: 'bash'
    waitFor: ['tests:integration']
    args: ['./scripts/run-integration-tests.sh']
  #tests cleanup
  - name: 'docker/compose:1.28.2'
    args: 
      [
        '-f',
        'docker-compose.yml',
        'down'
      ]
    id: 'tests:cleanup'
    waitFor: ['tests:e2e']  
  #push image
  - name: gcr.io/cloud-builders/docker
    id: "push"
    waitFor: ["tests:cleanup"]
    args:
      [
        "push",
        "$_IMAGE_NAME"
      ]
  #deploy to cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ["push"]
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_IMAGE_NAME'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '4040'
      - --vpc-connector 
      - $_VPC_CONNECTOR
