steps:
  #prepare .env file
  - name: node:14.17.1
    id: "setup-env-vars"
    entrypoint: npm
    args: ["run","create-env"]
    env:
      - PORT=$_PORT
      - REDIS_PORT=$_REDIS_PORT
      - REDIS_HOST=$_REDIS_HOST
      - AUTH0_SECRET=$_AUTH0_SECRET
      - ENVIRONMENT=$_TEST
  #build server
  - name: gcr.io/cloud-builders/docker
    id: "signout-backend"
    waitFor: ['setup-env-vars']
    args:
      [
        "build",
        "-f",
        "Dockerfile",
        "-t",
        "$_IMAGE_NAME",
        ".",
      ]
  #run docker-compose
  - name: 'docker/compose:1.28.2'
    args: 
      [
        '-f',
        'docker-compose.yml',
        'up', 
        '-d'
      ]
    id: 'tests:docker-compose'
    waitFor: ['signout-backend']
  #run integration tests
  - name: gcr.io/cloud-builders/npm
    id: 'tests:integration'
    waitFor: ['tests:docker-compose']
    args: ['npm run test']
  #run e2e tests
  - name: gcr.io/cloud-builders/npm
    id: 'tests:e2e'
    waitFor: ['tests:integration']
    args: ['npm run test-e2e']
  #tests cleanup
  - name: 'docker/compose:1.28.2'
    args: 
      [
        '-f',
        'docker-compose.yml',
        'down'
      ]
    id: 'tests:cleanup'
    waitFor: ['tests:e2e']  
  #push image
  - name: gcr.io/cloud-builders/docker
    id: "push"
    waitFor: ["signout-backend"]
    args:
      [
        "push",
        "$_IMAGE_NAME"
      ]
  #deploy to cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ["push"]
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_IMAGE_NAME'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '4040'
      - --vpc-connector 
      - $_VPC_CONNECTOR
