version: '3.8'

services:
    signout:
        build: ./
        links:
            - redis
        ports:
            - 4040:4040
        environment:
            - REDIS_HOST=redis
            - NODE_ENV=development
            - PORT=4040
            - AESKEY=AESKEYAESKEYAESKEYAESKEYAESKEY12
            - AUTH0_SECRET=AUTH0_SECRET
        command:
            sh -c 'npm start'
        depends_on: 
            - redis
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
    mockserver:
        build: ./mockServer
        ports:
            - 5555:5555