
redis:
    image: redis
    container_name: cache
    expose:
      - 6379
service:
    build: ./
    links:
      - redis
    ports:
      - 4040:4040
    environment:
      - REDISHOST=redis
      - NODE_ENV=development
      - PORT=4040
    command:
      sh -c 'npm start'