version: '3.8'

services:
    service:
        build: ./
        links:
        - redis
        ports:
        - 4040:4040
        environment:
        - REDIS_HOST=redis
        - NODE_ENV=development
        - PORT=4040
        command:
            sh -c 'npm start'
        depends_on: redis
    redis:
        image: redis
        container_name: redis
        expose:
        - 6379
    mockServer:
        build: ./mockServer